require_relative '../resource'

module Convection
  module Model
    class Template
      class Resource
        ##
        # AWS::RDS::EventSubscription
        # AWS_RDS_EventSubscription
        ##
        class RDSEventSubscription < Resource


          # @!scope class
          # @attribute [w]
          # Enabled
          # Indicates whether to activate the subscription. If you don't specify this                   property, AWS CloudFormation activates the subscription. -- WIP 
          # @note Required: No
          # @see  
          property :enabled, 'Enabled'

          # @!scope class
          # @attribute [w]
          # SnsTopicArn
          # The Amazon Resource Name (ARN) of an Amazon SNS topic that you want to send event                   notifications to. -- WIP 
          # @note Required: Yes
          # @see  
          property :sns_topic_arn, 'SnsTopicArn'

          # @!scope class
          # @attribute [w]
          # SourceType 
          # The type of source for which Amazon RDS provides notification events. For example,                   if you want to be notified of events generated by a database instance, set this                   parameter to db-instance. If you don't specify a value, notifications                   are provided for all source types. -- WIP 
          # @note Required: Conditional. If you specify the SourceIds or                      EventCategories property, you must specify this property.
          # @see  
          property :source_type , 'SourceType '

          # @!scope class
          # @attribute [w]
          # EventCategories
          # A list of event categories that you want to subscribe to for a given source                   type. If you don't specify this property, you are notified about all event                   categories. -- WIP
          # @note Required: No
          # @see 
          property :event_categories, 'EventCategories', :array

          # @!scope class
          # @attribute [w]
          # SourceIds
          # A list of identifiers for which Amazon RDS provides notification events. -- WIP
          # @note Required: No
          # @see 
          property :source_ids, 'SourceIds', :array


          def initialize(*args)
            super
            type 'RDSEventSubscription'
          end
        end
      end
    end
  end

  module DSL
    module Template
      # DESCRIPTION -- WIP
      # The following resources are available:
      # {Model::Template::Resource::RDSEventSubscription#enabled enabled}
      # {Model::Template::Resource::RDSEventSubscription#sns_topic_arn sns_topic_arn}
      # {Model::Template::Resource::RDSEventSubscription#source_type  source_type }
      # {Model::Template::Resource::RDSEventSubscription#event_categories event_categories}
      # {Model::Template::Resource::RDSEventSubscription#source_ids source_ids}
      # @see http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-eventsubscription.html 
      # @see {Model::Template::Resource::RDSEventSubscription}
      def rds_eventsubscription(name, &block)
        r = Model::Template::Resource::RDSEventSubscription.new(name, self)
        r.instance_exec(&block) if block
        resources[name] = r
      end
    end
  end
end
